[phases.setup]
nixPkgs = ["nodejs_24", "npm-9_x"]

[phases.install]
cmds = ["npm install --legacy-peer-deps"]

[phases.build]
cmds = ["npm run build --if-present"]

[start]
cmd = "cd apps/backend && npm start"
