[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = [
  "npm install -g pnpm corepack",
  "corepack enable",
  "cd .. && pnpm install --frozen-lockfile"
]

[phases.build]
cmds = [
  "cd .. && pnpm build:shared",
  "pnpm run build"
]

[start]
cmd = "node dist/server.js"
