[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = [
  "npm install -g pnpm corepack",
  "corepack enable",
  "NODE_ENV=development pnpm install --no-frozen-lockfile"
]

[phases.build]
cmds = [
  "pnpm build:shared",
  "cd apps/admin && pnpm run build",
  "cd apps/mandate-service && pnpm run build"
]

[start]
cmd = "cd apps/mandate-service && node dist/server.js"
